SET SERVEROUTPUT ON 
DECLARE
    NOME_ALUNO ALUNO.NOME%TYPE;
    RM_ALUNO ALUNO.RM%TYPE;
BEGIN
    FOR ALUNOS IN(SELECT * FROM ALUNO)
    LOOP
    NOME_ALUNO := ALUNOS.NOME;
    RM_ALUNO := ALUNOS.RM;
    DBMS_OUTPUT.PUT_LINE('Nome do Aluno: ' || NOME_ALUNO || ' - ' || 'RM do Aluno: ' || RM_ALUNO);
    END LOOP;
END;
