SET SERVEROUTPUT ON;
DECLARE
V_ALUNO VARCHAR2(100);

BEGIN
    SELECT NOME
        INTO V_ALUNO
        FROM ALUNO
        WHERE RM = 111222333;

    DBMS_OUTPUT.PUT_LINE('O NOME DO ALUNO É '|| V_ALUNO);

END;