SET SERVEROUTPUT ON;
-- TABUADA COM PÓS-CONDIÇÃO
DECLARE
    V_NUMERO NUMBER (3) := &DIGITE_UM_NUMERO;
    V_CONTADOR NUMBER (3) := 0;
BEGIN
    LOOP
    V_CONTADOR := V_CONTADOR + 1;
    DBMS_OUTPUT.PUT_LINE(V_CONTADOR || ' X ' || V_NUMERO || ' = ' || V_CONTADOR * V_NUMERO);
    EXIT WHEN(V_CONTADOR = 10);
    END LOOP;
END;